# -*- coding: utf-8 -*-
"""mBERT(figurative).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojKKPgUc8WxMcIHwklpgUSlLbRgdmyLY
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My\ Drive/PhD/

!pip install transformers datasets torchtext fasttext gensim scikit-learn matplotlib seaborn

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer, BertModel
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve
import matplotlib.pyplot as plt
import seaborn as sns
from gensim.models import KeyedVectors

# Load emotion dataset
from sklearn.utils import shuffle
df = pd.read_csv("/content/drive/My Drive/PhD/preprocessed_dataset.csv")
df= shuffle(df)
print("Sample Dataset:", df.shape)
df.head(20)

texts = df['Sentence'].astype(str).tolist()
labels = df['label'].astype(str).tolist()

from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

le = LabelEncoder()
y = le.fit_transform(labels)
y_cat = to_categorical(y)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_words = 10000
max_len = 100

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
X = pad_sequences(sequences, maxlen=max_len)

#!wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.am.300.bin.gz
#!gunzip cc.am.300.bin.gz  # Unzip if it's a .gz file

!wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.am.300.vec.gz
!gunzip cc.am.300.vec.gz  # Unzip if it's a .gz file

# Load FastText .venc file
import gensim
from gensim.models import KeyedVectors

fasttext_model = gensim.models.KeyedVectors.load_word2vec_format("cc.am.300.vec", binary=False)

#fasttext_model= fasttext_model1 or fasttext_model2
embedding_dim = 300
word_index = tokenizer.word_index
embedding_matrix = np.zeros((max_words, embedding_dim))

for word, i in word_index.items():
    if i < max_words:
        if word in fasttext_model:
            embedding_matrix[i] = fasttext_model[word]

# Get FastText embedding
from gensim.models import KeyedVectors
def get_fasttext_embedding(text):
    # Ensure text is a string before splitting
    if not isinstance(text, str):
        # Handle non-string types (e.g., NaN, numbers).
        # You can return a zero vector, or an empty list to be averaged into a zero vector.
        # For simplicity, if it's not a string, treat it as an empty string.
        text = ""

    words = text.split()
    word_vectors = [fasttext_model[word] for word in words if word in fasttext_model]

    if not word_vectors:
        # Return a zero vector of the correct dimension if no words found or text was empty
        if hasattr(fasttext_model, 'vector_size'):
            return np.zeros(fasttext_model.vector_size)
        else:
            return np.zeros(300) # Fallback, assume 300 if vector_size not directly available

    vec = np.mean(word_vectors, axis=0)
    return vec

df['fasttext'] = df['Sentence'].apply(get_fasttext_embedding)

# Label encoding
labels = df['label'].unique()
label2id = {label: idx for idx, label in enumerate(labels)}
id2label = {idx: label for label, idx in label2id.items()}
df['label_id'] = df['label'].map(label2id)

# Tokenizer from mBERT
tokenizer = BertTokenizer.from_pretrained("bert-base-multilingual-cased")

class AmharicDataset(Dataset):
    def __init__(self, texts, labels, fasttext_embeddings):
        self.encodings = tokenizer(texts.tolist(), truncation=True, padding=True, max_length=128)
        self.labels = labels.tolist()
        self.fasttext_embeddings = np.stack(fasttext_embeddings.tolist())

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        item['fasttext'] = torch.tensor(self.fasttext_embeddings[idx], dtype=torch.float32)
        return item

    def __len__(self):
        return len(self.labels)

# Split dataset
from sklearn.model_selection import train_test_split

train_texts, temp_texts, train_labels, temp_labels, train_ft, val_ft = train_test_split(
    df['Sentence'], df['label_id'], df['fasttext'], test_size=0.2, stratify=df['label_id']
)

val_texts, test_texts, val_labels, test_labels, val_ft, test_ft = train_test_split(
    df['Sentence'], df['label_id'], df['fasttext'], test_size=0.5, stratify=df['label_id']
)

train_dataset = AmharicDataset(train_texts, train_labels, train_ft)
val_dataset = AmharicDataset(val_texts, val_labels, val_ft)
test_dataset = AmharicDataset(test_texts, test_labels, test_ft)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)
test_loader = DataLoader(test_dataset, batch_size=16)

# Model: extend mBERT to concatenate FastText features
class mBERTWithFastText(torch.nn.Module):
    def __init__(self, num_labels):
        super(mBERTWithFastText, self).__init__()
        self.bert = BertModel.from_pretrained("bert-base-multilingual-cased")
        self.fc = torch.nn.Linear(self.bert.config.hidden_size + 300, 128)
        self.classifier = torch.nn.Linear(128, num_labels)
        self.dropout = torch.nn.Dropout(0.5)

    def forward(self, input_ids, attention_mask, fasttext, labels=None):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = outputs.pooler_output
        combined = torch.cat((pooled_output, fasttext), dim=1)
        x = self.dropout(self.fc(combined))
        logits = self.classifier(x)
        loss = None
        if labels is not None:
            loss_fn = torch.nn.CrossEntropyLoss()
            loss = loss_fn(logits, labels)
        return (loss, logits) if loss is not None else logits

import torch
from torch.optim import AdamW # This is the corrected import

# Rest of your code
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = mBERTWithFastText(num_labels=len(labels)).to(device)
optimizer = AdamW(model.parameters(), lr=2e-5)



import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import AutoModel
class MBERTFastTextClassifier(nn.Module):
    def __init__(self, model_name, ft_dim, num_labels):
        super().__init__()
        self.bert = AutoModel.from_pretrained(model_name)
        self.layernorm = nn.LayerNorm(self.bert.config.hidden_size + ft_dim)
        self.dropout = nn.Dropout(0.3)

        # Two-layer classifier with GELU
        self.fc1 = nn.Linear(self.bert.config.hidden_size + ft_dim, 768)
        self.gelu1 = nn.GELU()
        self.fc2 = nn.Linear(768, 256)
        self.gelu2 = nn.GELU()
        self.fc3 = nn.Linear(256, num_labels)

    def forward(self, input_ids, attention_mask, ft_vec):
        bert_out = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        cls_output = bert_out.last_hidden_state[:, 0, :]

        # normalize & scale FastText embeddings
        ft_vec = F.normalize(ft_vec, p=2, dim=1) * 1.0

        combined = torch.cat((cls_output, ft_vec), dim=1)
        combined = self.layernorm(combined)

        x = self.fc1(combined)
        x = self.gelu1(x)
        x = self.dropout(x)
        x = self.fc2(x)
        x = self.gelu2(x)
        x = self.dropout(x)
        logits = self.fc3(x)
        return logits



from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = MBERTFastTextClassifier(MODEL_NAME, 300, num_labels=3).to(DEVICE)

# Separate learning rates for BERT vs classifier
optimizer = AdamW([
    {"params": model.bert.parameters(), "lr": 2e-5},   # slightly higher
    {"params": list(model.fc1.parameters()) + list(model.fc2.parameters()) + list(model.fc3.parameters()), "lr": 2e-3}
], weight_decay=0.01)

criterion = nn.CrossEntropyLoss(label_smoothing=0.1)

EPOCHS = 100
total_steps = len(train_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=int(0.1 * total_steps),
    num_training_steps=total_steps
)







# ======================================
# STEP 7: Training Loop
# ======================================
EPOCHS = 100
from tqdm import tqdm

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0
    for batch in tqdm(train_loader, desc=f"Training Epoch {epoch+1}/{EPOCHS}"):
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(DEVICE)
        attention_mask = batch['attention_mask'].to(DEVICE)
        ft_vec = batch['fasttext'].to(DEVICE)
        labels = batch['labels'].to(DEVICE)

        outputs = model(input_ids, attention_mask, ft_vec)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        scheduler.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1} Loss: {total_loss/len(train_loader):.4f}")

# model Evaluation

import numpy as np
from sklearn.metrics import roc_auc_score

def evaluate(model, dataloader):
    model.eval()  # Set model to evaluation mode
    all_labels = []
    all_preds = []
    all_probs = []

    with torch.no_grad():
        for batch in dataloader:
            inputs = batch['input_ids'].to(DEVICE)
            attention_mask = batch['attention_mask'].to(DEVICE)  # Assuming this is part of your input
            ft_vec = batch['fasttext'].to(DEVICE)  # Assuming this is part of your input as well
            labels = batch['labels'].to(DEVICE)

            outputs = model(inputs, attention_mask=attention_mask, ft_vec=ft_vec)  # Call with all required inputs

            probs = torch.softmax(outputs, dim=1)  # Convert logits to probabilities
            preds = torch.argmax(probs, dim=1)  # Get the predicted class

            all_labels.extend(labels.cpu().numpy())
            all_preds.extend(preds.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())

    # Convert lists to numpy arrays
    all_labels = np.array(all_labels)
    all_preds = np.array(all_preds)
    all_probs = np.array(all_probs)

    # Check the shape of all_probs
    if all_probs.ndim == 1:
        all_probs = all_probs.reshape(-1, 1)

    auc = roc_auc_score(all_labels, all_probs, multi_class='ovr')  # Adjust as necessary
    report = classification_report(all_labels, all_preds, digits=4)


    print(report)

    return all_labels, all_preds, all_probs, auc

# ======================================
# STEP 9: Test Performance
# ======================================
labels, preds, probs, auc = evaluate(model, test_loader)
print(f'ROC AUC Score: {auc:.4f}')

model.summary()

# ======================================
# STEP 10: Confusion Matrix & ROC Curve
# ======================================
# ... (inside the STEP 10 cell)

cm = confusion_matrix(labels, preds)
plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    # Update x and y tick labels for 3 classes
    xticklabels=["Literal","Idiom", "Proverb"],
    yticklabels=["Literal","Idiom", "Proverb"]
)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("mBERT Confusion Matrix (Amharic figurative expressions - 3 Classes)")
plt.show()

# ======================================
# STEP 10: Confusion Matrix & ROC Curve
# ======================================
# ... (inside the STEP 10 cell)

cm = confusion_matrix(labels, preds)
plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    # Update x and y tick labels for 3 classes
    xticklabels=["Literal","Idiom", "Proverb"],
    yticklabels=["Literal","Idiom", "Proverb"]
)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("mBERT Confusion Matrix (Amharic figurative expressions - 3 Classes)")
plt.show()

